# Dataset
train_path: .data/train.csv
test_path: .data/test.csv

# Hyper parameter
backbone: resnet18
enable_gcn: true
drop_last: false

epochs: 100
batch_size: 80
num_workers: 1
lr: 0.01
momentum: 0.9
num_classes: 10
train_rate: 0.80

step_size: 10
gamma: 0.95

# Result
out_file: submit.csv

# Summary
runtime_id: null
sum_freq: 200
sum_validate_freq: 50